leave-management/ViewModels/LeaveAllocation/LeaveAllocationEditionViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using LeaveManagement.ViewModels.LeaveType;
using Microsoft.AspNetCore.Mvc;
using LeaveManagement.ViewModels.Employee;

namespace LeaveManagement.ViewModels.LeaveAllocation {
    public class LeaveAllocationEditionViewModel {
        [HiddenInput(DisplayValue = false)]
        public long Id { get; set; }

        [Required]
        [Display(Name = "Duration of leave", Description ="Number of days of this vacation", ShortName ="# Days", Prompt ="")]
        public int NumberOfDays { get; set; }

        [Required(AllowEmptyStrings =false, ErrorMessage ="Must be not empty")]
        [Display(Name ="Allocation date")]
        [DataType(DataType.Date, ErrorMessage ="Must be valid Date")]
        public DateTime DateCreated { get; set; }

        [Display(Description ="Employee who wants to leave", Name ="Employee")]
        public EmployeePresentationDefaultViewModel AllocationEmployee { get; set; }

        [Display(Description = "Employee who wants to leave", Name = "Employee")]
        public string AllocationEmployeeId { get; set; }

        [Display(Description = "List of employees", Name = "Employees")]
        public IEnumerable<SelectListItem> Employees { get; set; }

        [Display(Description = "Employee who wants to leave", Name = "Employee")]
        public LeaveTypeNavigationViewModel AllocationLeaveType { get; set; }

        [Display(Description = "Leave type", Name = "Leave type")]
        public int AllocationLeaveTypeId { get; set; }

        [Display(Description = "Leace Types", Name = "Leave types")]
        public IEnumerable<SelectListItem> AllocationLeaveTypes { get; set; }

        [Display(Description = "Period of leave", Name = "Period")]
        public int Period { get; set; }

    }
}

leave-management/ViewModels/LeaveAllocation/LeaveAllocationLeaveTypesListViewModel.cs
using System.Collections.Generic;
using LeaveManagement.ViewModels.LeaveType;

namespace LeaveManagement.ViewModels.LeaveAllocation {
    public class LeaveAllocationLeaveTypesListViewModel {
        public LeaveAllocationLeaveTypesListViewModel() {
            AvalableLeaveTypes = new List<LeaveTypeNavigationViewModel>();
        }

        public List<LeaveTypeNavigationViewModel> AvalableLeaveTypes { get; set; }
    }
}

leave-management/ViewModels/LeaveAllocation/LeaveAllocationViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using LeaveManagement.ViewModels.LeaveType;
using System.ComponentModel;
using LeaveManagement.ViewModels.Employee;

namespace LeaveManagement.ViewModels.LeaveAllocation {
    public class LeaveAllocationPresentationViewModel {

        [Display(Name ="ID", Description ="Identity number of this allocation", ShortName ="#")]
        public long Id { get; set; }

        [Display(Name = "Duration of leave", Description = "Duration of leave", ShortName = "Duration")]
        public uint NumberOfDays { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Date of apply", Description = "Date when employee asked for leave", ShortName = "Appl. Date")]
        public DateTime DateCreated { get; set; }

        [Display(Name ="Employee", Description ="Employee asking for leave")]
        public EmployeePresentationDefaultViewModel AllocationEmployee { get; set; }

        [Display(Name = "Date of apply", Description = "Date when employee asked for leave", ShortName = "Appl. Date")]
        public string AllocationEmployeeId { get; set; }

        [Display(Name = "Leave type", Description = "Reason to leave")]
        public LeaveTypeNavigationViewModel AllocationLeaveType { get; set; }

        public int AllocationLeaveTypeId { get; set; }

        [Display(Name ="Period of leave", Description = "Year of leave")]
        public int Period { get; set; }

    }
}

leave-management/Controllers/LeaveRequestsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using LeaveManagement.Code.CustomLocalization;
using LeaveManagement.Contracts;
using LeaveManagement.Data.Entities;
using LeaveManagement.ViewModels.Employee;
using LeaveManagement.ViewModels.LeaveRequest;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Math.EC.Rfc7748;

namespace LeaveManagement.Controllers {
    [Authorize]
    [MiddlewareFilter(typeof(LocalizationPipeline))]
    public class LeaveRequestsController : Controller {

        private const string StatisticsView = "ModeratorIndex";
        private const string ReviewViewName = "Review";

        #region Dependencies
        private readonly ILeaveRequestsRepositoryAsync _LeaveRequestsRepository;
        private readonly IMapper _Mapper;
        private readonly ILeaveManagementCustomLocalizerFactory _LocalizerFactory;
        private readonly IStringLocalizer _ControllerLocalizer;

        private readonly UserManager<IdentityUser> _UserManager;
        private readonly ILeaveTypeRepositoryAsync _LeaveTypeRepository;
        private readonly ILeaveAllocationRepositoryAsync _LeaveAllocationsRepository;
        private readonly IEmployeeRepositoryAsync _EmployeeRepository;

        public LeaveRequestsController(
            ILeaveRequestsRepositoryAsync leaveRequestsRepository,
            IMapper mapper,
            ILeaveManagementCustomLocalizerFactory localizerFactory,
            UserManager<IdentityUser> userManager,
            ILeaveTypeRepositoryAsync leaveTypeRepository,
            ILeaveAllocationRepositoryAsync leaveAllocationRepository,
            IEmployeeRepositoryAsync employeeRepository) {
            _LeaveRequestsRepository = leaveRequestsRepository;
            _Mapper = mapper;
            _LocalizerFactory = localizerFactory;
            _UserManager = userManager;
            _LeaveTypeRepository = leaveTypeRepository;
            _LeaveAllocationsRepository = leaveAllocationRepository;
            _ControllerLocalizer = _LocalizerFactory.Create(this.GetType());
            _EmployeeRepository = employeeRepository;
        }
        #endregion

        [HttpGet]
        public async Task<IActionResult> Index() {
            var currentUser = _UserManager.GetUserAsync(User);
            var leaveRequests = await _LeaveRequestsRepository.WhereAsync(x => x.RequestingEmployeeId.Equals(currentUser.Id));
            var leaveRequestsModel = _Mapper.Map<List<LeaveRequestDefaultViewModel>>(leaveRequests);
            LeaveRequestsStatisticsViewModel leaveRequestsStatistics = new LeaveRequestsStatisticsViewModel() {
                Moderation = false,
                LeaveRequests = leaveRequestsModel,
                TotalRequests = leaveRequests.Count,
                AcceptedRequests = leaveRequests.Count(x => x.Approuved == true),
                RejectedRequests = leaveRequests.Count(x => x.Approuved == false),
                PendingRequests = leaveRequests.Count(x => x.Approuved is null)
            };
            return View(leaveRequestsStatistics);
        }

        [HttpGet]
        public async Task<IActionResult> ModeratorIndex() {
            var currentEmployee = await _EmployeeRepository.GetEmployeeAsync(User);
            if(currentEmployee == null) {
                ModelState.AddModelError("", _ControllerLocalizer["Your account not belongs to employees"]);
                return Forbid();
            }
            if (!await _UserManager.IsCompanyPrivelegedUser(currentEmployee)) {
                ModelState.AddModelError("", _ControllerLocalizer["Your role not allows you to administrate leave requests"]);
                return Forbid();
            }
   
            var leaveRequests = await _LeaveRequestsRepository.WhereAsync(lr=>lr.LeaveType?.CompanyId == currentEmployee.CompanyId &&
            lr.RequestingEmployee?.CompanyId == currentEmployee.CompanyId);
            var leaveRequestsModel = _Mapper.Map<List<LeaveRequestDefaultViewModel>>(leaveRequests);
            ViewBag.DisplayReviewButton = true;
            LeaveRequestsStatisticsViewModel leaveRequestsStatistics = new LeaveRequestsStatisticsViewModel() {
                Moderation = true,
                LeaveRequests = leaveRequestsModel,
                TotalRequests = leaveRequests.Count,
                AcceptedRequests = leaveRequests.Count(x => x.Approuved == true),
                RejectedRequests = leaveRequests.Count(x => x.Approuved == false),
                PendingRequests = leaveRequests.Count(x => x.Approuved is null)
            };
            return View(leaveRequestsStatistics);
        }

        [HttpGet]
        public async Task<IActionResult> Create() {
            var currentEmployee = await _EmployeeRepository.GetEmployeeAsync(User);
            if (currentEmployee == null) {
                ModelState.AddModelError("", _ControllerLocalizer["Your account not belongs to employees"]);
                return Forbid();
            }
            var createLeaveRequestViewModel = new CreateLeaveRequestVM();
            var leaveTypes = await _LeaveTypeRepository.WhereAsync(x=>x.CompanyId == currentEmployee.CompanyId);
            createLeaveRequestViewModel.LeaveTypes = _Mapper.Map<List<SelectListItem>>(leaveTypes);
            createLeaveRequestViewModel.StartDate = DateTime.Now.Date;
            createLeaveRequestViewModel.EndDate = DateTime.Now.AddDays(7).Date;
            return View(createLeaveRequestViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateLeaveRequestVM leaveRequest) {
            
            var currentEmployee = await _EmployeeRepository.GetEmployeeAsync(User);
            if (currentEmployee == null) {
                ModelState.AddModelError("", _ControllerLocalizer["Your account not belongs to employees"]);
                return Forbid();
            }
            if (!ModelState.IsValid) {
                return View(leaveRequest);
            }
            leaveRequest.LeaveTypes = _Mapper.Map<IEnumerable<SelectListItem>>(await _LeaveTypeRepository.WhereAsync(c=>c.CompanyId == currentEmployee.CompanyId));

            if (DateTime.Compare(leaveRequest.StartDate, leaveRequest.EndDate) > 1) {
                ModelState.AddModelError("Date", _ControllerLocalizer["Start date must be earlier that the end date"]);
                return View(leaveRequest);
            }


            if (!await ValidateRequestDaysAsync(currentEmployee.Id, (int)leaveRequest.LeaveTypeId, leaveRequest.StartDate, leaveRequest.EndDate)) {
                ModelState.AddModelError("", _ControllerLocalizer["You have requested more days that you owned"]);
                return View(leaveRequest);
            }
            var request = new LeaveRequest() {
                ActionedDateTime = null,
                Approuved = null,
                ApprouvedBy = null,
                ApprouvedById = null,
                LeaveTypeId = (int)leaveRequest.LeaveTypeId,
                RequestedDate = DateTime.Now,
                StartDate = leaveRequest.StartDate,
                EndDate = leaveRequest.EndDate,
                RequestingEmployeeId = currentEmployee.Id,
                RequestComment = leaveRequest.RequestComment,
            };

            if (!await _LeaveRequestsRepository.CreateAsync(request)) {
                ModelState.AddModelError("", _ControllerLocalizer[
                    @"Something went wrong when submitting your request. Please wait a moment and retry or contact your system administrator"]);
                return View(leaveRequest);
            }
            else
                return RedirectToAction(nameof(EmployeeRequests));
        }


        [HttpGet]
        public async Task<IActionResult> Review(int requestId) {
            var currentEmployee = await _EmployeeRepository.GetEmployeeAsync(User);
            if (currentEmployee == null) {
                ModelState.AddModelError("", _ControllerLocalizer["Your account not belongs to employees"]);
                return Forbid();
            }
            if (!await _UserManager.IsCompanyPrivelegedUser(currentEmployee)) {
                ModelState.AddModelError("", _ControllerLocalizer["Your role not allows you to administrate leave requests"]);
                return Forbid();
            }
            var leaveRequest = await _LeaveRequestsRepository.FindByIdAsync(requestId);
            if (leaveRequest == null)
                return NotFound(_ControllerLocalizer["Leave request #{0} was not found", requestId]);
            var currentUser = await _UserManager.GetUserAsync(User);
            if (!await _UserManager.IsCompanyPrivelegedUser(currentUser))
                return Forbid(_ControllerLocalizer["Your role not allows you to administrate leave requests"]);
            var viewModel = _Mapper.Map<LeaveRequestDefaultViewModel>(leaveRequest);
            viewModel.RequestingEmployee = _Mapper.Map<EmployeePresentationDefaultViewModel>(leaveRequest.RequestingEmployee);
            viewModel.ApprouvedBy = _Mapper.Map<EmployeePresentationDefaultViewModel>(leaveRequest.ApprouvedBy);
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Review(int requestId, LeaveRequestDefaultViewModel viewModel) {
            var currentEmployee = await _EmployeeRepository.GetEmployeeAsync(User);
            if (currentEmployee == null) {

leave-management/Views/LeaveAllocation/AllocateByLeaveTypes.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model LeaveManagement.ViewModels.LeaveAllocation.LeaveAllocationLeaveTypesListViewModel;


@{
    ViewData["Title"] = Localizer["Leave allocation"];
}
<h1>@Localizer["Which type of leave would-loke you allocate?"]</h1>
<table class="table dataTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(mdl => mdl.AvalableLeaveTypes.FirstOrDefault().LeaveTypeName)</th>
            <th>@Html.DisplayNameFor(mdl => mdl.AvalableLeaveTypes.FirstOrDefault().DefaultDays)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var leaveType in Model.AvalableLeaveTypes)
        {
            <tr>
                <td>@leaveType.LeaveTypeName</td>
                <td>@leaveType.DefaultDays</td>
                <td>
                    <a asp-action="CreateByLeaveType" asp-route-leaveType="@leaveType.Id" class="btn btn-outline-success"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Allocate {0}", leaveType.LeaveTypeName]">
                        <i class="fa fa-calendar"></i>
                    </a>
                    <a asp-action="CreateAllocationToAllEmployees" asp-route-leaveTypeId="@leaveType.Id" class="btn btn-outline-info"
                       onclick="confirm(@LeaveManagementLocalizerFactory.CommandsLocalizer["Are you sure you want to allocate this leave type to all employees?"])"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Allocate {0} to all employees",  leaveType.LeaveTypeName]">
                        <i class="fa fa-user-plus"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

leave-management/Views/LeaveAllocation/CreateLeaveAllocation.cshtml
@using LeaveManagement.Controllers;
@model LeaveManagement.ViewModels.LeaveAllocation.LeaveAllocationEditionViewModel;
@inject Microsoft.AspNetCore.Identity.UserManager<Microsoft.AspNetCore.Identity.IdentityUser> _UserManager;


@{
    ViewData["Title"] = Localizer["Allocate leave by its type"];
}

<h1>@Localizer["Allocate leave by its type"]</h1>

<h4>@Localizer["Leave allocation"]</h4>
<hr />

<partial name="_ProblemPartial" />

<div class="row">
    <div class="col-md-4">
        <partial name="_ProblemPartial" />
        <form asp-action="@ViewBag.Action">
            <!--CreateNewByLeaveType-->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" disabled />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
                <input type="hidden" asp-for="DateCreated" />
            </div>
            <div class="form-group">
                <label asp-for="AllocationEmployee" class="control-label"></label>
                @if (ViewBag.CanEditEmployee ?? false)
                {
                    <select asp-for="AllocationEmployeeId" asp-items="Model.Employees" class="form-control custom-select"></select>
                }
                else
                {
                    <input type="text" class="form-control" value="@Model.AllocationEmployee.FormatEmployeeSNT()" disabled />
                    <input type="hidden" asp-for="AllocationEmployeeId" />
                }
            </div>

            <div class="form-group">
                <label asp-for="AllocationLeaveType.LeaveTypeName" class="control-label"></label>
                @if (ViewBag.CanEditLeaveType ?? false)
                {
                    <select asp-for="AllocationLeaveTypeId" asp-items="Model.AllocationLeaveTypes" class="form-control custom-select"></select>
                    <span asp-validation-for="AllocationLeaveTypeId" class="text-danger"></span>
                }
                else
                {
                    <input asp-for="AllocationLeaveType.LeaveTypeName" class="form-control" disabled />
                    <input type="hidden" asp-for="AllocationLeaveTypeId" />
                }
            </div>

            <div class="form-group">
                <label asp-for="Period" class="control-label"></label>
                @if (ViewBag.CanEditPeriod ?? false)
                {
                    <input asp-for="Period" class="form-control" />
                    <span asp-validation-for="Period" class="text-danger"></span>
                }
                else
                {
                    <input asp-for="Period" class="form-control" disabled />
                    <input type="hidden" asp-for="Period" />
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>


leave-management/Views/LeaveAllocation/Details.cshtml
@model LeaveManagement.ViewModels.LeaveAllocation.LeaveAllocationPresentationViewModel

@{
    ViewData["Title"] = @Localizer["Details of leave allocations"];
}

<h1>@Localizer["Details of leave allocations"]</h1>

<div>
    <h4>LeaveAllocationPresentationViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDays)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AllocationEmployee)
        </dt>
        <dd class = "col-sm-10">
            <span>@Model.AllocationEmployee.FormatEmployeeSNT()</span>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AllocationLeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AllocationLeaveType.LeaveTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Period)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Period)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-block btn-warning" asp-action="Edit" asp-route-id="@Model.Id">
        <i class="fa fa-pencil"></i>&nbsp;@LeaveManagementLocalizerFactory.CommandsLocalizer["Edit"]
    </a>
    
    <a class="btn btn-block btn-info" asp-action="UserLeaveAllocationsForPeriod">
    <i class="fa fa-list"></i> &nbsp;@LeaveManagementLocalizerFactory.CommandsLocalizer["Back to List"]</a>
</div>

leave-management/Views/LeaveAllocation/UserLeaveAllocationsForPeriod.cshtml
@model IEnumerable<LeaveManagement.ViewModels.LeaveAllocation.LeaveAllocationPresentationViewModel>

@{
    ViewData["Title"] = Localizer["Yours leave allocations"];
}
@if (ViewBag.ShowRequestButton)
{
    <div class="row">
        <div class="col-md-4 offset-md-8">
            <a class="btn btn-block btn-outline-success" asp-controller="LeaveRequests" asp-action="Create">
                @LeaveManagementLocalizerFactory.CommandsLocalizer["Request for leave"]
            </a>
        </div>
    </div>
    <br />
    <hr />
}


<h1>@Localizer["List of your leave allocation"]</h1>

<table class="table dataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AllocationLeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Period)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AllocationEmployee)

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="UserLeaveAllocationsForPeriod"
                       asp-route-leaveTypeId="@item.AllocationLeaveTypeId"
                       asp-route-period="*"
                       asp-route-userId="*">
                        @item.AllocationLeaveType?.LeaveTypeName
                    </a>
                </td>
                <td>
                    <a asp-action="UserLeaveAllocationsForPeriod" asp-route-period="@item.Period">
                        @Html.DisplayFor(modelItem => item.Period)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    <a asp-action="UserLeaveAllocationsForPeriod" asp-route-userId="@item.AllocationEmployeeId">
                        <span>@item.AllocationEmployee.FormatEmployeeSNT()</span>
                    </a>
                </td>
                <td>
                        @if (await _UserManager.IsCompanyPrivelegedUser(User))
                        {
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-block">
                                <i class="fa fa-pencil"></i> @LeaveManagementLocalizerFactory.CommandsLocalizer["Edit"]
                            </a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-block btn-danger"
                               onclick="return confirm('@Localizer["Are you sure you want to delete this allocation?"]')">
                                <i class="fa fa-trash"></i>@LeaveManagementLocalizerFactory.CommandsLocalizer["Delete"]
                            </a>
                        }
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-block btn-success">
                                <i class="fa fa-sun-o"></i> @LeaveManagementLocalizerFactory.CommandsLocalizer["Details"]
                            </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="container container-fluid">
    <div class="row">
        <div class="col col-5">
            <a asp-action="UserLeaveAllocationsForPeriod" asp-route-period="*" asp-route-userId="*" asp-route-leaveTypeId="@null" class="btn btn-outline-info btn-block">
                <i class="fa fa-dedent"></i> @Localizer["Show all"]
            </a>
        </div>
    </div>
</div>
@section Styles{
    <partial name="_DataTablesStyles" />
}
@section Scripts{
    <partial name="_DataTablesScripts" />
}