leave-management/ViewModels/Employee/EmployeeCreationVM.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace LeaveManagement.ViewModels.Employee {

    public class EmployeeCreationVM  {


        [HiddenInput]
        public string Id { get; set; }

        [HiddenInput]
        public string ReturnUrl { get; set; }

        public bool AccountDataEnabled { get; set; } = true;

        [Display(Name = "User name", Description = "The main user name which will be displayed like your login", ShortName = "Login", Prompt = "Enter user name")]
        [DataType(DataType.Text)]
        [MinLength(6)]
        [MaxLength(50)]
        [Required(ErrorMessage = "User name is required")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Principal email", Prompt ="Your email", Description = "Your principal email, which you can ")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }


        public bool ProfileDataEnabled { get; set; } = true;

        [Required]
        [Display(Name = "Employee title", Description = "M., Ms., Mrs., Miss", Prompt = "Employee title")]
        public string Title { get; set; }

        [Required(ErrorMessage ="First name required")]
        [Display(Name = "First name", Description = "Users' first name", Prompt = "Enter first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name required")]
        [Display(Name = "Last name", Description = "Last (family) name", Prompt = "Enter last(family) name")]
        public string LastName { get; set; }

        [Display(Name = "Tax of employee", Prompt = "Enter tax rate", Description = "Tax rate")]
        public string TaxRate { get; set; }

        [Required(ErrorMessage = "Date of birth cant be empty")]
        [Display(Name = "Date of birth", Prompt = "Date of birth of employee", Description = "Date of birth of employee")]
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [Display(Name = "Date of employement", Prompt = "Employement date", Description = "Date of employement")]
        [DataType(DataType.Date)]
        public DateTime EmploymentDate { get; set; } = DateTime.Now;

        public bool ContactDataEnabled { get; set; } = true;

        [Required(ErrorMessage = "Phone number required")]
        [Display(Name = "Phone number", Description = "Phone", Prompt ="Enter phone number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Contact mail", Prompt = "Please enter contact mail", Description = "Contact mail can be used as alternative mail")]
        [DataType(DataType.EmailAddress)]
        public string ContactMail { get; set; }

        #region Roles
        public bool RolesListEnabled { get; set; } = true;

        [Display(Name = "Roles", Prompt = "Roles", Description ="Function of this employee")]
        public IEnumerable<SelectListItem> RolesList { get; set; }

        public IList<string> Roles { get; set; }

        [Required(ErrorMessage ="You must accept contract")]
        [Display(Name = "Agree to all conditions", Prompt = "Accept th conditions", Description = "Accept the conditions of thez contract")]
        public bool AcceptContract { get; set; }
        #endregion

        #region Company
        public virtual bool CompanyEnabled { get; set; } = false;

        [Display(Name ="Company", Prompt="Please assign employee to the company", Description ="Employees company")]
        public int? CompanyId { get; set; }

        public Data.Entities.Company Company { get; set; }

        [Display(Name = "Company", Prompt = "Please assign employee to the company", Description = "Employees company")]
        public IEnumerable<SelectListItem> Companies { get; set; }
        #endregion

        #region Manager
        public bool ManagerEnabled { get; set; }

        [Display(Name = "Manager id", Prompt = "Please assign employee to the company", Description = "Employees' manager")]
        public string ManagerId { get; set; }

        [Display(Name = "Manager id", Prompt = "Please assign employee to the company", Description = "Employees' manager")]
        public EmployeeCreationVM Manager { get; set; }

        [Display(Name = "Manager", Prompt = "Please choose the manager", Description = "Employee manager")]
        public IEnumerable<SelectListItem> Managers { get; set; }
        #endregion
    }
}

leave-management/ViewModels/Employee/EmployeePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LeaveManagement.ViewModels.Employee {
    public class EmployeePassword {

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Old password", Prompt = "Enter your password", Description = "Old password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password", Prompt = "Your password", Description = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password", Prompt = "Confirm your password", Description = "Confirm your password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

leave-management/Controllers/EmployeeController.cs
using AutoMapper;
using LeaveManagement.Contracts;
using LeaveManagement.Data.Entities;
using LeaveManagement.PasswordGenerator;
using LeaveManagement.ViewModels.Employee;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Resources;
using System.Threading.Tasks;

namespace LeaveManagement.Controllers {
    [MiddlewareFilter(typeof(LocalizationPipeline))]
    public class EmployeeController : Controller {

        private const string RegisterEmployeeView = "Create";
        private const string EditEmployeeView = "Edit";

        private readonly SignInManager<IdentityUser> _SignInManager;
        private readonly UserManager<IdentityUser> _UserManager;
        private readonly RoleManager<IdentityRole> _RoleManager;
        private readonly ILogger<EmployeePresentationDefaultViewModel> _Logger;
        private readonly IEmailSender _EmailSender;
        private readonly IEmployeeRepositoryAsync _EmployeeRepository;
        private readonly IStringLocalizer _DataLocalizer;
        private readonly IMapper _Mapper;
        private readonly IPasswordGenerator _PasswordGenerator;
        private readonly ICompanyRepository _CompanyRepository;

        public EmployeeController(SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,
            RoleManager<IdentityRole> roleManager,
            ILogger<EmployeePresentationDefaultViewModel> logger,
            IEmailSender emailSender,
            IEmployeeRepositoryAsync employeeRepository,
            IStringLocalizerFactory localizerFactory,
            IMapper mapper,
            IPasswordGenerator passwordGenerator,
            ICompanyRepository companyRepository) {
            _SignInManager = signInManager;
            _UserManager = userManager;
            _RoleManager = roleManager;
            _Logger = logger;
            _EmailSender = emailSender;
            _EmployeeRepository = employeeRepository;
            _DataLocalizer = localizerFactory.Create(typeof(Areas.Identity.Pages.Account.RegisterModel));
            _Mapper = mapper;
            _PasswordGenerator = passwordGenerator;
            _CompanyRepository = companyRepository;
        }

        string ReturnUrl = "";
        #region Service methods
        private async Task<UserRoles> GetAllowedRolesAsync(UserRoles currentUserMembership, bool self) {
            return await Task.Run(() => {
                UserRoles result = UserRoles.None;
                if ((currentUserMembership & UserRoles.AppAdministrator) == UserRoles.AppAdministrator)
                    result |= (UserRoles.CompanyAdministrator | UserRoles.AppAdministrator);
                if ((currentUserMembership & UserRoles.CompanyAdministrator) == UserRoles.CompanyAdministrator)
                    result |= (UserRoles.CompanyAdministrator | UserRoles.Employee | UserRoles.HRManager);
                if ((currentUserMembership & UserRoles.HRManager) == UserRoles.HRManager)
                    result |= UserRoles.Employee;
                if (self)
                    result |= currentUserMembership;
                return result;
            });
        }

        private async Task<IEnumerable<SelectListItem>> GetListAllowedRoles(UserRoles currentUserRoles = UserRoles.None, bool self = false) {
            UserRoles allowedRoles = await GetAllowedRolesAsync(currentUserRoles, self);
            var userRolesValues = Enum.GetValues(typeof(UserRoles));
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            foreach (object userRoleObj in userRolesValues) {
                UserRoles userRole = (UserRoles)userRoleObj;
                selectListItems.Add(new SelectListItem() {
                    Text = _DataLocalizer[userRole.ToString()],
                    Value = userRole.ToString(),
                    Selected = (currentUserRoles & userRole) == userRole,
                    Disabled = (userRole & allowedRoles) == UserRoles.None
                });
            }
            return selectListItems;
        }
        #endregion


        #region Creating Employees
        [HttpGet]
        public async Task<IActionResult> CreateEmployee() {
            ReturnUrl = HttpContext.Request.Headers["Referer"];
            var currentCredentials = await GetCurrentUserData();
            var editionPermissions = await GetEditionPermission(null);
            if (!editionPermissions.AllowEdition) {
                ModelState.AddModelError("", _DataLocalizer["Action permitted only to administrators"]);
                return Forbid();
            }
            EmployeeCreationVM employeeCreationVM = new EmployeeCreationVM() {
                EmploymentDate = DateTime.Now,
                AcceptContract = false,
                ReturnUrl = Request.Headers["Referer"].ToString(),
                RolesList = await GetListAllowedRoles(),
                Roles = new List<string>()
            };
            //
            if (currentCredentials.Item2?.CompanyId != null) {
                employeeCreationVM.CompanyId = currentCredentials.Item2.CompanyId;
                if (currentCredentials.Item2?.Company != null)
                    employeeCreationVM.Company = currentCredentials.Item2.Company;
                else
                    employeeCreationVM.Company = await _CompanyRepository.FindByIdAsync((int)employeeCreationVM.CompanyId);
            }
            //Case when new employee created inside the company
            employeeCreationVM = await SetEmployeeCompanyAndManagerState(employeeCreationVM, editionPermissions);
            employeeCreationVM.RolesListEnabled = editionPermissions.AllowEditAccess;
            employeeCreationVM.RolesList = await GetListAllowedRoles(currentCredentials.Item3, self: editionPermissions.IsSelfEdition);
            ViewBag.Action = nameof(CreateEmployee);
            return View(RegisterEmployeeView, employeeCreationVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateEmployee(EmployeeCreationVM employeeCreationVM) {

            string referer = employeeCreationVM.ReturnUrl;
            var currentPermissions = await GetEditionPermission(null);
            var currentUserData = await GetCurrentUserData();
            //Validating access
            if (!ValidateCreationAccess(currentUserData.Item3))
                return Forbid();
            //Validating duplicates
            await ValidateDuplicateMail(employeeCreationVM.Email);
            await ValidateDuplicateUserName(employeeCreationVM.UserName);
            //Validating contract
            ValidateContractAcceptence(employeeCreationVM.AcceptContract);
            //Validating is company and manager correctly assigned
            await ValidateEmployeeCreationVMState(employeeCreationVM);
            UserRoles employeeRoles = await ValidateAssignedRoles(LeaveManagementExtensions.ToUserRoles(employeeCreationVM.Roles), null);
            if (ModelState.ErrorCount > 0) {
                employeeCreationVM.RolesList = await GetListAllowedRoles(employeeRoles);
            }
            if (ModelState.ErrorCount == 0) {
                Employee employee = new Employee();
                employeeCreationVM.Id = employee.Id;
                employee = (Employee)_Mapper.Map(employeeCreationVM, typeof(EmployeeCreationVM), typeof(Employee));
                string password = _PasswordGenerator.GeneratePassword();
                employee.LockoutEnabled = false;
                employee.EmailConfirmed = true;
                bool result = await _EmployeeRepository.RegisterEmployeeAsync(employee, password);
                if (!result)
                    ModelState.AddModelError("", _DataLocalizer["Unabled to save employee into repository"]);
                else
                    await SendMailWithCredentials(employee, password);
            }
            //Validating user roles
            if (ModelState.ErrorCount == 0) {
                var employeeIdentityUser = await _UserManager.FindByEmailAsync(employeeCreationVM.Email);
                var newRoles = LeaveManagementExtensions.FromUserRoles(employeeRoles).ToList();
                foreach (var role in newRoles) {
                    var identityResult = await _UserManager.AddToRoleAsync(employeeIdentityUser, role);
                    if (!identityResult.Succeeded)
                        ModelState.AddModelError("", _DataLocalizer["Unable to add this user to role {0}", role]);
                };
            }

            if (ModelState.ErrorCount > 0) {
                employeeCreationVM = await SetEmployeeCompanyAndManagerState(employeeCreationVM, currentPermissions);
                employeeCreationVM.RolesListEnabled = currentPermissions.AllowEditAccess;
                employeeCreationVM.RolesList = await GetListAllowedRoles(currentUserData.Item3, self: currentPermissions.IsSelfEdition);
                ViewData["Referer"] = referer;
                ViewBag.Action = nameof(CreateEmployee);
                return View(RegisterEmployeeView, employeeCreationVM);
            }
            else {
                if (!String.IsNullOrEmpty(referer))
                    return Redirect(referer);
                else
                    return RedirectToAction("Index", "Home");
            }

        }

        private bool ValidateCreationAccess(UserRoles currentUserRoles) {
            bool allowed = (currentUserRoles & (UserRoles.AppAdministrator | UserRoles.CompanyAdministrator | UserRoles.HRManager)) > 0;
            if (!allowed) {

leave-management/Views/Employee/Details.cshtml
@model LeaveManagement.ViewModels.Employee.EmployeeCreationVM

@{
    ViewData["Title"] = "Details";
    ViewData[LeaveManagement.ManageNavPages.Employees] = LeaveManagement.ManageNavPages.Employees;
}

<h1>Details</h1>

<div>
    <h4>EmployeeCreationVM</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ContactMail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ContactMail)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TaxRate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TaxRate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmploymentDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmploymentDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

leave-management/Views/Employee/Index.cshtml
@model IEnumerable<LeaveManagement.ViewModels.Employee.EmployeePresentationDefaultViewModel>
@{
    ViewData["Title"] = Localizer["Allocate by employees"];
    ViewData[LeaveManagement.ManageNavPages.Employees] = LeaveManagement.ManageNavPages.Employees;
}
<a class="btn btn-outline-primary" asp-controller="Employee" asp-action="CreateEmployee" title="@LeaveManagementLocalizerFactory.MenuLocalizer["Create employee"]">
    <i class="fa fa-user nav-icon"></i>
</a>
<hr />
<h1>@Localizer["Employees"]</h1>

<table class="table dataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmploymentDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @if (!String.IsNullOrWhiteSpace(item.ContactMail))
                    {
                        @Html.DisplayFor(modelItem => item.ContactMail)
                    }

                    else
                    {
                        @Html.DisplayFor(modelItem => item.Email)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmploymentDate)
                </td>
                <td>
                    <a class="btn btn-outline-info" asp-action="UpdateEmployee" asp-route-employeeId="@item.Id"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Edit employee"]">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-outline-info" asp-action="Delete" asp-route-employeeId="@item.Id"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Edit employee"]">
                        <i class="fa fa-remove"></i>
                    </a>

                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <partial name="_DataTablesScripts" />
}
@section Styles{
    <partial name="_DataTablesStyles" />
}

leave-management/Views/Employee/IndexForYourCompany.cshtml
@model IEnumerable<LeaveManagement.ViewModels.Employee.EmployeePresentationDefaultViewModel>
@{
    ViewData["Title"] = Localizer["Allocate by employees"];
    ViewData[LeaveManagement.ManageNavPages.ActivePageSection] = LeaveManagement.ManageNavPages.Employees;
}
<a class="btn btn-outline-primary" asp-controller="Employee" asp-action="CreateEmployee" title="@LeaveManagementLocalizerFactory.MenuLocalizer["Create employee"]">
    <i class="fa fa-user nav-icon"></i>
</a>
<hr />
<h1>@Localizer["Employees"]</h1>

<table class="table dataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmploymentDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @if (!String.IsNullOrWhiteSpace(item.ContactMail))
                    {
                        @Html.DisplayFor(modelItem => item.ContactMail)
                    }

                    else
                    {
                        @Html.DisplayFor(modelItem => item.Email)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmploymentDate)
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-controller="LeaveAllocation" asp-action="AllocateByEmployee" asp-route-employeeId="@item.Id"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Allocate leave"]">
                        <i class="fa fa-calendar"></i>
                    </a>

                    <a class="btn btn-outline-info" asp-action="UpdateEmployee" asp-route-employeeId="@item.Id"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Edit employee"]">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-outline-info" asp-action="Delete" asp-route-employeeId="@item.Id"
                       title="@LeaveManagementLocalizerFactory.CommandsLocalizer["Edit employee"]">
                        <i class="fa fa-remove"></i>
                    </a>


                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts{
    <partial name="_DataTablesScripts" />
}
@section Styles{
    <partial name="_DataTablesStyles" />
}