leave-management/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using LeaveManagement.Contracts;
using LeaveManagement.Data.Entities;
using LeaveManagement.ViewModels.Company;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;

namespace LeaveManagement.Controllers {
    [Authorize]
    public class CompanyController : Controller {
        private readonly ICompanyRepository _CompanyRepository;
        private readonly IEmployeeRepositoryAsync _EmpoyeeRepository;
        private readonly ILeaveTypeRepositoryAsync _LeaveTypeRepository;
        private readonly SignInManager<IdentityUser> _SignInManager;
        private readonly UserManager<IdentityUser> _UserManager;
        private readonly ILogger<CompanyController> _CompanyControllerLogger;
        private readonly IStringLocalizer _MessageLocalizer;
        private readonly IMapper _Mapper;
        private readonly IEmailSender _EmailSender;

        private const string EditionViewName = "Edit";

        public CompanyController(
            ICompanyRepository companyRepository,
            IEmployeeRepositoryAsync employeeRepository,
            SignInManager<IdentityUser> signInManager,
            UserManager<IdentityUser> userManager,
            ILogger<CompanyController> logger,
            IStringLocalizerFactory localizerFactory,
            IMapper mapper,
            IEmailSender emailSender,
            ILeaveTypeRepositoryAsync leaveTypeRepository) {
            _CompanyRepository = companyRepository;
            _EmpoyeeRepository = employeeRepository;
            _UserManager = userManager;
            _SignInManager = signInManager;
            _CompanyControllerLogger = logger;
            _MessageLocalizer = localizerFactory.Create(this.GetType());
            _Mapper = mapper;
            _EmailSender = emailSender;
            _LeaveTypeRepository = leaveTypeRepository;
        }

        // GET: CompanyController
        [HttpGet]
        public async Task<ActionResult> Index(bool showDisabled = false) {
            var currentUser = await _UserManager.GetUserAsync(User);
            if (!(await _UserManager.IsMemberOfOneAsync(currentUser, UserRoles.AppAdministrator))) {
                _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to browse companies");
                ModelState.AddModelError("", _MessageLocalizer["Your not allowed to list the companies"]);
                return Forbid();
            }
            IEnumerable<CompanyVM> companies = _Mapper.Map<List<CompanyVM>>(await _CompanyRepository.WhereAsync(c => c.Active || showDisabled));
            return View(companies);
        }

        // GET: CompanyController/Details/5
        public async Task<ActionResult> Details(int id) {
            var currentUser = await _UserManager.GetUserAsync(User);
            UserRoles currentUserRoles = await _UserManager.GetUserRolesAsync(currentUser);
            var currentEmployee = await _EmpoyeeRepository.FindByIdAsync(currentUser.Id);
            bool userAuthorizedToViewDetails = currentEmployee != null || currentEmployee?.CompanyId == id
                || (await _UserManager.IsMemberOfOneAsync(currentUser, UserRoles.AppAdministrator));
            if (!userAuthorizedToViewDetails) {
                _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to browse companies");
                ModelState.AddModelError("", _MessageLocalizer["Your not allowed to show the details of this company"]);
                return Forbid();
            }
            var companyData = await _CompanyRepository.FindByIdAsync(id);
            if (companyData == null) {
                _CompanyControllerLogger.LogWarning($"Company {id} was not found");
                ModelState.AddModelError("", _MessageLocalizer["Company not found"]);
                return NotFound();
            }
            CompanyVM companyVM = _Mapper.Map<CompanyVM>(companyData);
            if ((currentUserRoles & (UserRoles.AppAdministrator | UserRoles.CompanyAdministrator)) == 0)
                companyVM.CompanyProtectedComment = _MessageLocalizer["Hidden"];
            return View(companyVM);
        }

        // GET: CompanyController/Create
        public async Task<ActionResult> Create() {
            var currentUser = await _UserManager.GetUserAsync(User);
            UserRoles currentUserRoles = await _UserManager.GetUserRolesAsync(currentUser);
            bool roleAllowsCreateCompany = (currentUserRoles & UserRoles.AppAdministrator) == UserRoles.AppAdministrator;
            if (!roleAllowsCreateCompany) {
                _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to create the company record");
                ModelState.AddModelError("", _MessageLocalizer["Your not allowed to create the companies"]);
                return Forbid();
            }
            CompanyVM companyVM = new CompanyVM() { Id = 0, CompanyRegistrationDate = DateTime.Now, Active=true };
            ViewData["Action"] = nameof(Create);
            return View(EditionViewName, companyVM);
        }

        // POST: CompanyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CompanyVM companyVM) {
            try {
                var currentUser = await _UserManager.GetUserAsync(User);
                UserRoles currentUserRoles = await _UserManager.GetUserRolesAsync(currentUser);
                bool roleAllowsCreateCompany = (currentUserRoles & UserRoles.AppAdministrator) == UserRoles.AppAdministrator;
                if (!roleAllowsCreateCompany) {
                    _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to create company record");
                    ModelState.AddModelError("", _MessageLocalizer["Your not allowed to create the companies"]);
                    return Forbid();
                }
                Company company = _Mapper.Map<Company>(companyVM);
                if (!(await _CompanyRepository.CreateAsync(company))) {
                    ModelState.AddModelError("", _MessageLocalizer["Unabled to create the company due the server error"]);
                    _CompanyControllerLogger.LogError("Unabled to create the company due the server error");
                }

                return RedirectToAction(nameof(Index));
            }
            catch {
                ViewData["Action"] = nameof(Create);
                return View(EditionViewName, companyVM);
            }
        }

        // GET: CompanyController/Edit/5
        public async Task<ActionResult> Edit(int id) {
            var currentUser = await _UserManager.GetUserAsync(User);
            UserRoles currentUserRoles = await _UserManager.GetUserRolesAsync(currentUser);
            var currentEmployee = await _EmpoyeeRepository.FindByIdAsync(currentUser.Id);
            bool roleAllowsEditCompanyData = ((currentUserRoles & UserRoles.AppAdministrator) == UserRoles.AppAdministrator)
                || (((currentUserRoles & UserRoles.CompanyAdministrator) == UserRoles.CompanyAdministrator) && currentEmployee?.CompanyId != id);
            if (!roleAllowsEditCompanyData) {
                _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to browse companies");
                ModelState.AddModelError("", _MessageLocalizer["Your not allowed to show the details of this company"]);
                return Forbid();
            }
            var companyData = await _CompanyRepository.FindByIdAsync(id);
            if (companyData == null) {
                _CompanyControllerLogger.LogWarning($"Company {id} was not found");
                ModelState.AddModelError("", _MessageLocalizer["Company not found"]);
                return NotFound();
            }
            CompanyVM companyVM = _Mapper.Map<CompanyVM>(companyData);
            ViewData["Action"] = nameof(Edit);
            return View(EditionViewName, companyVM);
        }

        // POST: CompanyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, CompanyVM companyVM) {
            try {
                var currentUser = await _UserManager.GetUserAsync(User);
                UserRoles currentUserRoles = await _UserManager.GetUserRolesAsync(currentUser);
                var currentEmployee = await _EmpoyeeRepository.FindByIdAsync(currentUser.Id);
                bool roleAllowsEditCompanyData = ((currentUserRoles & UserRoles.AppAdministrator) == UserRoles.AppAdministrator)
                    || (((currentUserRoles & UserRoles.CompanyAdministrator) == UserRoles.CompanyAdministrator) && currentEmployee?.CompanyId != id);
                if (!roleAllowsEditCompanyData) {
                    _CompanyControllerLogger.LogWarning($"User {currentUser.UserName} was forbidden to browse companies");
                    ModelState.AddModelError("", _MessageLocalizer["Your not allowed to show the details of this company"]);
                    return Forbid();
                }
                var companyData = await _CompanyRepository.FindByIdAsync(id);
                if (companyData == null) {
                    _CompanyControllerLogger.LogWarning($"Company {id} was not found");
                    ModelState.AddModelError("", _MessageLocalizer["Company not found"]);
                    return NotFound();
                }

leave-management/Views/Shared/_AdminLTELayout.cshtml
@using Microsoft.AspNetCore.Identity;
@using LeaveManagement.CustomLocalization;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject LeaveManagement.Contracts.ILeaveRequestsRepositoryAsync LeaveRequests
@{
    IdentityUser AppUser = SignInManager.IsSignedIn(User) ? await UserManager.GetUserAsync(User) : null;
    IList<string> UserRoles = AppUser != null ? await UserManager.GetRolesAsync(AppUser) : null;
    Microsoft.AspNetCore.Routing.RouteValueDictionary CurrentRoute = Context.Request.RouteValues;
}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>@Localizer["Leave management"]</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/lib/fontawesome47/css/font-awesome.min.css" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/admin-lte/dist/css/adminlte.min.css" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="~/lib/flag-icon-css/css/flag-icon.min.css" rel="stylesheet" />
    @RenderSection("Styles", false)
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fa fa-bars"></i></a>
                </li>




            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                <partial name="_Notifications" />
                <!--Langudage dropdown menu-->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-globe" title="@Localizer["Language"]"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header">@Localizer["Please chose your language"]</span>
                        @foreach (var culture in GlobalizationStartup.SupportedCultures)
                        {
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Home" asp-action="SwitchCulture" asp-route-cultureCode="@culture.Name"
                               asp-route-refController="@(CurrentRoute.ContainsKey("controller")? CurrentRoute["controller"] :"")"
                               asp-route-refAction="@(CurrentRoute.ContainsKey("action")? CurrentRoute["action"] :"")"
                               asp-route-refId="@(CurrentRoute.ContainsKey("id")? CurrentRoute["id"] :"")">
                                <i class="@culture.GetFlagIconsCountryCode("flag-icon flag-icon-{0}")"></i> @culture.DisplayName
                            </a>
                        }
                    </div>
                </li>


            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <i class="fa fa-2x fa-compass"></i>
                <span class="brand-text font-weight-light">@LeaveManagementLocalizerFactory.MenuLocalizer["Leave management"]</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <partial name="_LoginAdminLTEPartial" />
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon fa fa-home"></i>
                                <p>
                                    @LeaveManagementLocalizerFactory.MenuLocalizer["Home"]
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">
                                <i class="nav-icon fa fa-home"></i>
                                <p>
                                    @LeaveManagementLocalizerFactory.MenuLocalizer["Help"]
                                </p>
                            </a>
                        </li>
                        @if (await UserManager.IsMemberOfOneAsync(User, LeaveManagement.UserRoles.Employee | LeaveManagement.UserRoles.HRManager | LeaveManagement.UserRoles.CompanyAdministrator))
                        {
                            <li class="nav-item">
                                <a asp-controller="LeaveRequests" asp-action="Create" class="nav-link">
                                    <i class="nav-icon fa fa-hotel"></i>
                                    <p>
                                        @LeaveManagementLocalizerFactory.MenuLocalizer["Apply for leave"]
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="LeaveRequests" asp-action="EmployeeRequests" class="nav-link">
                                    <i class="nav-icon fa fa-calculator"></i>
                                    <p>
                                        @LeaveManagementLocalizerFactory.MenuLocalizer["My leaves"]
                                    </p>
                                </a>
                            </li>

                        }
                        @if (await UserManager.IsMemberOfOneAsync(User, LeaveManagement.UserRoles.AppAdministrator))
                        {
                            <li class="nav-item">
                                <a asp-controller="Company" asp-action="Index" class="nav-link">
                                    <i class="nav-icon fa fa-building"></i>
                                    <p>
                                        @LeaveManagementLocalizerFactory.MenuLocalizer["Manage companies"]
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Employee" asp-action="CreateEmployee" class="nav-link">
                                    <i class="nav-icon fa fa-user-plus"></i>
                                    <p>
                                        @LeaveManagementLocalizerFactory.MenuLocalizer["Create company admin"]
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Employee" asp-action="Index">
                                    <i class="fa fa-users nav-icon"></i>
                                    <p>@LeaveManagementLocalizerFactory.MenuLocalizer["Users"]</p>
                                </a>
                            </li>
                        }
                        @if (await _UserManager.IsCompanyPrivelegedUser(User))
                        {
                            <li class="nav-item has-treeview menu-open">
                                <a href="#" class="nav-link active">
                                    <i class="nav-icon fa fa-tachometer"></i>
                                    <p>
                                        @LeaveManagementLocalizerFactory.MenuLocalizer["Administration"]
                                        <i class="right fa fa-angle-left"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="LeaveRequests" asp-action="ModeratorIndex">
                                            <i class="fa fa-low-vision nav-icon"></i>
                                            <p>@LeaveManagementLocalizerFactory.MenuLocalizer["Review requests"]</p>
                                            @if ((int?)ViewData["PendingRequests"] > 0)
                                            {
                                                <span class="badge badge-warning">@ViewData["PendingRequests"]</span>
                                            }
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-action="Index" asp-controller="LeaveTypes">
                                            <i class="fa fa-table nav-icon"></i>
                                            <p>@LeaveManagementLocalizerFactory.MenuLocalizer["Leave types"]</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="LeaveAllocation" asp-action="AllocateByLeaveTypes">
                                            <i class="fa fa-hotel nav-icon"></i>
                                            <p>@LeaveManagementLocalizerFactory.MenuLocalizer["Allocate leaves"]</p>
                                        </a>
                                    </li>
                                    <li class="nav-item active">
                                        <a class="nav-link" asp-controller="Employee" asp-action="IndexForYourCompany">
                                            <i class="fa fa-group nav-icon"></i>
                                            <p>@LeaveManagementLocalizerFactory.MenuLocalizer["Employees"]</p>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                        }

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">

                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>

            </div>
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                &copy; @DateTime.Now.Year - @Localizer["Leave management"] <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/admin-lte/dist/js/adminlte.min.js"></script>
    @await RenderSectionAsync("Scripts", false);
</body>
</html>

leave-management/Views/Shared/_DataTablesScripts.cshtml
@using System.Globalization;

<environment include="Development,LocalRelease">
    <script src="~/lib/dataTables/datatables.min.js"></script>
    <script src="~/lib/dataTables/DataTables-1.10.20/js/dataTables.bootstrap4.min.js"></script>
</environment>
<environment exclude="Development,LocalRelease">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
</environment>
<script src="~/lib/dataTables/lang/@(CultureInfo.CurrentCulture.TwoLetterISOLanguageName.ToLower()).js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.dataTable').DataTable({
            "language": dataTableLanguageOptions
        });
    });
</script>

leave-management/Views/Shared/_DataTablesStyles.cshtml
<environment include="Development,LocalRelease">
    <link href="~/lib/dataTables/datatables.min.css" rel="stylesheet" />
</environment>
<environment exclude="Development,LocalRelease">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
</environment>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

leave-management/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    IdentityUser AppUser = SignInManager.IsSignedIn(User) ? await UserManager.GetUserAsync(User) : null;
    IList<string> UserRoles = AppUser != null ? await UserManager.GetRolesAsync(AppUser) : null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["Leave management"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Developement">
        <link href="~/lib/fontawesome47/css/font-awesome.min.css" rel="stylesheet" />
    </environment>
    <environment exclude="Developement">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@LeaveManagementLocalizerFactory.MenuLocalizer["Leave management"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-controller="LeaveAllocation" asp-action="UserLeaveAllocationsForPeriod"
                               asp-route-showRequestButton="true" asp-route-userId="@null">
                                @LeaveManagementLocalizerFactory.MenuLocalizer["Your leave allocations"]
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="LeaveRequests" asp-action="Create">
                                @Localizer["Request leave"]
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="LeaveRequests" asp-action="EmployeeRequests">
                                @Localizer["My requests"]
                            </a>
                        </li>
                        @if (AppUser != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @LeaveManagementLocalizerFactory.MenuLocalizer["Manage"]
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (await UserManager.IsCompanyPrivelegedUser(AppUser))
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="LeaveTypes" asp-action="Index">
                                            @LeaveManagementLocalizerFactory.MenuLocalizer["Edit leave types"]
                                        </a>
                                        <a class="dropdown-item" asp-area="" asp-controller="LeaveAllocation" asp-action="AllocateByLeaveTypes">
                                            @Localizer["Allocate leaves"]
                                        </a>
                                    }
                                    @if (AppUser != null)
                                    {

                                        <a class="dropdown-item" asp-controller="LeaveAllocation" asp-action="UserLeaveAllocationsForPeriod">
                                            @LeaveManagementLocalizerFactory.MenuLocalizer["Browse your current allocations"]
                                        </a>

                                    }
                                    @if (UserRoles?.Contains(LeaveManagement.UserRoles.AppAdministrator.ToString()) ?? false)
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="LeaveRequests" asp-action="ModeratorIndex">
                                            @LeaveManagementLocalizerFactory.MenuLocalizer["Leave requests"]
                                        </a>
                                    }
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @Localizer["Leave management"] <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

leave-management/Views/Shared/_ProblemPartial.cshtml

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@if(!String.IsNullOrWhiteSpace(ViewBag.ErrorTitle) && !String.IsNullOrWhiteSpace(ViewBag.ErrorMessage)) {
    <div class="invalid-feedback">
        <h4>@ViewBag.ErrorTitle</h4>
        <p>
            @ViewBag.ErrorMessage
        </p>
    </div>
}